name: Deploy Images to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Store'
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/alekstet/store:latest
          docker push ghcr.io/alekstet/store:latest